### ISSUE TITLE
Fn::ImportValue in CF mock does not handle missing exports gracefully

### ISSUE THREAD

**Issue by tmwong2003** [spulec/moto#1657]
When creating a CloudFormation stack that imports a nonexistent export, `moto` throws an exception that seems unrelated to the issue at hand. For example, given the following CF template that imports the nonexistent export `SimpleSecurityGroup`:

```
Resources:
  SimpleInstance:
    Type: AWS::EC2::Instance
    Properties:
        ImageId: ami-03cf127a
        InstanceType: t2.micro
        SecurityGroups: !Split [',', !ImportValue SimpleSecurityGroup]
```

`moto` raises the following exception:

```
Traceback (most recent call last):
# ...
  File "/Users/theodorew/moto/moto/cloudformation/parsing.py", line 206, in clean_json
    values = [x.value for x in resources_map.cross_stack_resources.values() if x.name == cleaned_val]
AttributeError: 'list' object has no attribute 'values'
```

The underlying issues are two-fold:

1. `FakeStack` in `moto.cloudformation.models` sets the default value of the `cross_stack_resources` attribute to an empty list instead of an empty dict.
1. When parsing the `Fn::ImportValue` intrinsic function, `moto.cloudformation.parsing.clean_json()` simply drops out of the `if` block responsible for processing `Fn::ImportValue`, instead of raising an exception or returning some kind of empty value.

The sample code to trigger this issue is as follows:

```
import boto3
from moto import mock_cloudformation

EC2_STACK_NAME = 'simple-ec2-stack'
EC2_TEMPLATE = """
Resources:
  SimpleInstance:
    Type: AWS::EC2::Instance
    Properties:
        ImageId: ami-03cf127a
        InstanceType: t2.micro
        SecurityGroups: !Split [',', !ImportValue SimpleSecurityGroup]
"""


with mock_cloudformation():
    client = boto3.client('cloudformation')
    client.create_stack(StackName=EC2_STACK_NAME, TemplateBody=EC2_TEMPLATE)
```
