### ISSUE TITLE
NotImplementedError: The create_log_group action has not been implemented

### ISSUE THREAD

**Issue by christhomas** [spulec/moto#2323]
I'm trying to create a log group with the aws cli and I get this error

```
NotImplementedError: The create_log_group action has not been implemented
```

I was under the impression from the implemented table that this should work, I've tried compiling from the source code myself and I still get this error.

**Comment by spulec** [comment]
This should work. Can you add the commands you are using the run the server and to call the client?

**Comment by christhomas** [comment]
Sure, I'll try to make an example

**Comment by christhomas** [comment]
FYI: backbone has an nginx reverse proxy which I've configured with to let me access software on port 80, it's allowing me to use hostnames instead of ip addresses. I'm 100% sure this isn't anything that would interfere with this problem.

docker-compose.yml:
```
version: "3"

networks:
  backbone:
    external:
      name: backbone

services:
  cloudwatch:
    image: picadoh/motocker:latest
    networks:
      - backbone
    environment:
      - VIRTUAL_HOST=~^logs.([a-z0-9\-]+).aws.develop
      - VIRTUAL_PORT=5000
      - MOTO_SERVICE=cloudwatch
```

command line:
```
bash# AWS_ACCESS_KEY_ID=mock AWS_SECRET_ACCESS_KEY=mock aws --endpoint=http://logs.eu-west-1.aws.develop logs create-log-group --log-group-name=hello

An error occurred (500) when calling the CreateLogGroup operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```
