### ISSUE TITLE
SSM tag methods should error with InvalidResourceId if not there

### ISSUE THREAD

**Issue by jeking3** [spulec/moto#4360]
In #1024 changes were made to emulate tagging methods in the ssm subsystem.  Unfortunately they do not behave like AWS does.  When a resource is not available, AWS returns an `InvalidResourceId` error.  Here is an example I recorded with vcrpy:

```
  request:
    method: POST
    uri: https://ssm.us-west-2.amazonaws.com/
    body: '{"ResourceType": "Parameter", "ResourceId": "special-not-there-4"}'
  response:
    body:
      string: '{"__type":"InvalidResourceId"}'
    status:
      code: 400
      message: Bad Request
```

Here is the response from moto, which is incorrect:

```
(Pdb) pp client.list_tags_for_resource(ResourceType="Parameter", ResourceId="special-not-there-4")
{'ResponseMetadata': {'HTTPHeaders': {'server': 'amazon.com'},
                      'HTTPStatusCode': 200,
                      'RetryAttempts': 0},
 'TagList': []}
```
