### ISSUE TITLE
INFO: some moto 3 dependencies have breaking changes

### ISSUE THREAD

**Issue by dazza-codes** [spulec/moto#4894]
After a recent update to moto 3, some dependencies of moto3 are breaking tests.  So far, some useful pins are a work around, e.g.

```toml
[tool.poetry.dev-dependencies]

moto = {version = "^3.0.0", extras = ["all","server"]}
flask = "^1.1.4"  # pinned to avoid test crashes
markupsafe = "2.0.1"  # 2.1.0 breaks Jinja2 - tests crash

```
